import { useState, useEffect } from 'react';
import { ComposableMap, Geographies, Geography, Marker, ZoomableGroup } from 'react-simple-maps';
import MetricCards from './components/MetricCards';
import AlertTable from './components/AlertTable';
import ChartsView from './components/ChartsView';
import GraphView from './components/GraphView';
import './index.css';

// IMPORT THE LOCAL OFFLINE MAP (Generated by 5_fetch_map.py)
import INDIA_TOPO_JSON from './india-states.json';

const API = 'http://localhost:8000/api/v1';

const dict = {
  en: {
    skip: "Skip to Main Content", gov: "Government of India", ntro: "National Technical Research Organisation",
    title: "ChainWatch", subtitle: "| Threat Intelligence",
    heroTitle: "National Crypto-Threat Intelligence Network",
    heroSub: "Securing India's digital financial infrastructure through AI-driven blockchain forensics and anomaly detection.",
    alerts: "ALERTS", secure: "SECURE OFFLINE", about: "About the Platform",
    aboutText: "ChainWatch is an advanced AI-powered offline intelligence system designed by NTRO to monitor, detect, and analyze illicit cryptocurrency transaction traffic.",
    quickLinks: "Quick Links", nodalAgency: "Nodal Agency",
    copyright: "© 2026 National Technical Research Organisation, Government of India. All rights reserved."
  }
};

const INDIAN_STATES = ['Delhi', 'Maharashtra', 'Karnataka', 'Gujarat', 'Tamil Nadu', 'West Bengal', 'Uttar Pradesh', 'Telangana', 'Kerala', 'Rajasthan'];

function useAPI(endpoint) {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    fetch(`${API}${endpoint}`).then(r => r.json()).then(setData).finally(() => setLoading(false));
  }, [endpoint]);
  return { data, loading };
}

export default function App() {
  const { data: stats, loading: statsLoading } = useAPI('/stats');
  const { data: apiAlerts, loading: alertsLoading } = useAPI('/anomalies?limit=50');
  const { data: clusters } = useAPI('/clusters');
  const { data: graphData, loading: graphLoading } = useAPI('/graph');

  const [alerts, setAlerts] = useState([]);
  useEffect(() => { if (apiAlerts) setAlerts(apiAlerts); }, [apiAlerts]);

  const [highlightedWallet, setHighlightedWallet] = useState(null);
  const [minConfidence, setMinConfidence] = useState(0);
  const [selectedCluster, setSelectedCluster] = useState(null);

  const [zoom, setZoom] = useState(1);
  const [liveThreatData, setLiveThreatData] = useState(null); // Holds the real threat data for the map
  const t = dict.en;

  // ── THE REAL DATA TRIGGER (Double Click Logo) ──
  const triggerLiveIsolation = () => {
    if (liveThreatData || !alerts || alerts.length === 0) return; 

    // Grab the actual #1 threat from your Python backend
    const realThreat = alerts[0];
    setLiveThreatData(realThreat);
    setHighlightedWallet(realThreat.wallet_address);

    // Auto-scroll to the map and table
    setTimeout(() => {
      const target = document.getElementById('threat-intel-section');
      if (target) target.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }, 500);
  };

  const filteredAlerts = alerts?.filter(a => {
    if (a.confidence_score < minConfidence) return false;
    if (selectedCluster !== null && a.cluster_id !== selectedCluster) return false;
    return true;
  });

  return (
    <div className="app-shell" style={{ zoom: zoom }}>
      
      {/* ── Accessibility Bar ── */}
      <div className="access-bar">
        <a href="#main-content" className="access-link">{t.skip}</a>
        <div className="access-group">
          <button onClick={() => setZoom(0.9)}>A-</button>
          <button onClick={() => setZoom(1)}>A</button>
          <button onClick={() => setZoom(1.1)}>A+</button>
        </div>
      </div>
      
      {/* ── Header & Trigger ── */}
      <header className="topbar">
        <div className="topbar-brand" onDoubleClick={triggerLiveIsolation} style={{ cursor: 'default' }}>
          <img src="https://upload.wikimedia.org/wikipedia/commons/5/55/Emblem_of_India.svg" alt="Emblem" style={{ height: '56px', filter: 'brightness(0) invert(1)' }} />
          <div className="brand-titles">
            <div className="brand-goi">{t.gov}</div>
            <div className="brand-name">{t.ntro}</div>
          </div>
        </div>
        <div className="topbar-actions">
          <div className="system-title">
            <span style={{ color: '#ffffff', fontWeight: 800 }}>{t.title}</span>
            <span style={{ color: '#94a3b8', fontWeight: 500, marginLeft: 8 }}>{t.subtitle}</span>
          </div>
          <span className="badge badge-success">✓ {t.secure}</span>
        </div>
      </header>

      {/* ── LIVE THREAT BANNER ── */}
      {liveThreatData && (
        <div className="live-threat-banner">
          ⚠️ CRITICAL ALERT: LIVE ANOMALY DETECTED IN {liveThreatData.primary_state?.toUpperCase() || 'INDIAN'} JURISDICTION. AUTO-ISOLATING NETWORK NODES...
        </div>
      )}

      <section className="hero-section">
        <div className="hero-overlay">
          <h1>{t.heroTitle}</h1>
          <p>{t.heroSub}</p>
        </div>
      </section>

      {/* ── State Ticker ── */}
      <div className="ticker-wrapper">
        <div className={`ticker-track ${liveThreatData ? 'paused' : ''}`}>
          {[...INDIAN_STATES, ...INDIAN_STATES].map((stateName, idx) => {
            const isTarget = liveThreatData && stateName === liveThreatData.primary_state;
            const regWallets = stats ? Math.floor(stats.total_wallets / 10) + (idx * 2) : 0;
            const regTxns = stats ? Math.floor(stats.total_transactions / 10) + (idx * 15) : 0;
            return (
              <div key={`${stateName}-${idx}`} className={`flash-card ${isTarget ? 'danger' : ''}`}>
                <div className="fc-header">
                  <span className="fc-title">📍 {stateName}</span>
                  <span className={`fc-dot ${isTarget ? 'blink-red' : 'green'}`}></span>
                </div>
                <div className="fc-body">
                  <div className="fc-stat"><span>Wallets:</span> <strong>{regWallets.toLocaleString()}</strong></div>
                  <div className="fc-stat"><span>TXNs:</span> <strong>{regTxns.toLocaleString()}</strong></div>
                  <div className="fc-stat alert-stat">
                    <span>Anomalies:</span> 
                    <strong style={{ color: isTarget ? 'var(--gov-red)' : 'var(--gov-green)' }}>{isTarget ? '1' : '0'}</strong>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </div>

      <main id="main-content" className="main-content">
        <MetricCards stats={statsLoading ? null : stats} />
        <ChartsView stats={stats} clusters={clusters} />

        {/* ── HYBRID INTELLIGENCE VIEW (Graph + Map) ── */}
        <div id="threat-intel-section" className="dashboard-grid two-column">
          
          <div className="card graph-card">
            <div className="card-header">
              <div className="card-title"><span className="card-title-icon">🛰️</span> Hybrid Threat Mapping</div>
            </div>
            
            <div className="hybrid-view-container">
              {/* Left: Force Graph */}
              <div className="hybrid-graph">
                <GraphView data={graphData} loading={graphLoading} highlightNode={highlightedWallet} />
              </div>

              {/* Right: Geographical Map */}
              <div className="hybrid-map">
                <ComposableMap projection="geoMercator" projectionConfig={{ scale: 1000, center: [80, 22] }} style={{ width: "100%", height: "100%" }}>
                  <ZoomableGroup 
                    center={liveThreatData && liveThreatData.lng ? [liveThreatData.lng, liveThreatData.lat] : [80, 22]} 
                    zoom={liveThreatData ? 5 : 1} 
                    transitionDuration={1200}
                  >
                    <Geographies geography={INDIA_TOPO_JSON}>
                      {({ geographies }) =>
                        geographies.map((geo) => {
                          // Smart Check: Ensure state highlights regardless of which JSON key is used
                          const stateName = geo.properties.st_nm || geo.properties.name || geo.properties.NAME_1;
                          const isThreatState = liveThreatData && stateName === liveThreatData.primary_state;
                          
                          return (
                            <Geography 
                              key={geo.rsmKey} 
                              geography={geo} 
                              fill={isThreatState ? "#fee2e2" : "#ffffff"} 
                              stroke="#cbd5e1" 
                              strokeWidth={1} 
                              style={{ default: { outline: "none" }, hover: { fill: "#f1f5f9", outline: "none" }, pressed: { outline: "none" } }}
                            />
                          );
                        })
                      }
                    </Geographies>
                    
                    {/* Pulsing Red Marker for the Threat (Native SVG Animation) */}
                    {liveThreatData && liveThreatData.lng && (
                      <Marker coordinates={[liveThreatData.lng, liveThreatData.lat]}>
                        <circle r={4} fill="#cc0000" />
                        <circle r={4} fill="none" stroke="#cc0000" strokeWidth={2}>
                          <animate attributeName="r" from="4" to="25" dur="1.5s" repeatCount="indefinite" />
                          <animate attributeName="opacity" from="1" to="0" dur="1.5s" repeatCount="indefinite" />
                        </circle>
                        <text textAnchor="middle" y={-12} style={{ fontFamily: "monospace", fill: "#990000", fontSize: "8px", fontWeight: "bold" }}>
                          {liveThreatData.primary_state.toUpperCase()}
                        </text>
                      </Marker>
                    )}
                  </ZoomableGroup>
                </ComposableMap>
              </div>
            </div>
          </div>

          {/* Alert Table */}
          <div className="card alert-panel">
            <div className="card-header">
              <div className="card-title"><span className="card-title-icon">🚨</span> Threat Watchlist</div>
              {filteredAlerts && <div className="badge badge-danger">{filteredAlerts.length} FOUND</div>}
            </div>
            <AlertTable 
              alerts={filteredAlerts} 
              loading={alertsLoading} 
              clusters={clusters}
              selectedWallet={highlightedWallet}
              onSelectWallet={(w) => {
                setHighlightedWallet(w);
                const threat = alerts.find(a => a.wallet_address === w);
                if (threat) setLiveThreatData(threat);
              }}
              minConfidence={minConfidence}
              onMinConfidenceChange={setMinConfidence}
              selectedCluster={selectedCluster}
              onClusterChange={setSelectedCluster}
            />
          </div>
        </div>
      </main>

      {/* ── Thick Official Footer ── */}
      <footer className="footer-main">
        <div className="footer-columns">
          <div className="footer-col">
            <h3>{t.about}</h3>
            <p>{t.aboutText}</p>
          </div>
          <div className="footer-col">
            <h3>{t.quickLinks}</h3>
            <ul>
              <li><a href="#">Dashboard Home</a></li>
              <li><a href="#">Generate Intelligence Report</a></li>
              <li><a href="#">Threat Pattern Database</a></li>
              <li><a href="#">User Manual & API Docs</a></li>
            </ul>
          </div>
          <div className="footer-col">
            <h3>{t.nodalAgency}</h3>
            <p>
              <strong>National Technical Research Organisation</strong><br/>
              Block-III, Old JNU Campus<br/>
              New Delhi - 110067<br/>
              Email: cyber-intel@ntro.gov.in
            </p>
          </div>
        </div>
        <div className="footer-bottom">
          <p>{t.copyright}</p>
          <div className="footer-bottom-links">
            <a href="#">Privacy Policy</a><span>|</span><a href="#">Terms of Use</a><span>|</span><a href="#">Security Policy</a>
          </div>
        </div>
      </footer>
    </div>
  );
}